version: "2.4"
services:
  plug:
    image: docker.package.tiredpixel.com/isoxya/isoxya-plugin-crawler-html-build:head
    volumes:
      - ./isx-plug-crawler-html.cabal:/home/x/repo/isx-plug-crawler-html.cabal
      - ./lib:/home/x/repo/lib
      - ./src:/home/x/repo/src
      - ./test:/home/x/repo/test
    networks:
      plug:
        aliases:
          - crawler-html.plugin.dev.isoxya.com
networks:
  plug:
    external: true
    name: isoxya_plug
